//
//  DataDemo.swift
//  ScholarshipDemo2
//
//  Created by Park Kangwook on 2022/06/24.
//

import Foundation

struct DataDemo {
//    var dataDemo : [String:[String:String]] =
//    ["간호대학":["간호학과":""],
//     "경영대학":["경영학과":""],
//     "경제통상대학":["경제학부":"",
//               "공공정책학부":"",
//               "관광컨벤션학과":"",
//               "국제학부":"",
//               "무역학부":""],
//     "공과대학":["건설융합학부 건축공학전공":"",
//             "건설융합학부 건축학전공":"",
//             "건설융합학부 도시공학전공":"",
//             "건설융합학부 토목공학전공":"",
//             "고분자공학과":"",
//             "기계공학부":"",
//             "산업공학과":"",
//             "유기소재시스템공학과":"",
//             "재료공학부":"",
//             "전기공학과":"",
//             "전자공학과":"",
//             "조선해양공학과":"",
//             "항공우주공학과":"",
//             "화공생명환경공학부 화공생명공학전공":"",
//             "화공생명환경공학부 환경공학전공":""],
//     "나노과학기술대학":["광메카트로닉스공학과":"",
//                 "나노메카트로닉스공학과":"",
//                 "나노에너지공학과":""],
//     "사범대학":["교육학과":"",
//             "국어교육과":"",
//             "독어교육과":"",
//             "물리교육과":"",
//             "불어교육과":"",
//             "생물교육과":"",
//             "수학교육과":"",
//             "역사교육과":"",
//             "영어교육과":"",
//             "유아교육과":"",
//             "윤리교육과":"",
//             "일반사회교육과":"",
//             "지구과학교육과":"",
//             "지리교육과":"",
//             "체육교육과":"",
//             "특수교육과":"",
//             "화학교육과":""],
//     "사회과학대학":["문헌정보학과":"",
//               "미디어커뮤니케이션학과":"",
//               "사회복지학과":"",
//               "사회학과":"",
//               "심리학과":"",
//               "정치외교학과":"",
//               "행정학과":""],
//     "생명자원과학대학":["동물생명자원과학과":"",
//                 "바이오산업기계공학과":"",
//                 "바이오소재과학과":"",
//                 "바이오환경에너지학과":"",
//                 "생명환경화학과":"",
//                 "식물생명과학과":"",
//                 "식품공학과":"",
//                 "식품자원경제학과":"",
//                 "원예생명과학과":"",
//                 "조경학과":"",
//                 "IT응용공학과":""],
//     "생활환경대학":["식품영양학과":"",
//               "실내환경디자인학과":"",
//               "아동가족학과":"",
//               "의류학과":""],
//     "스포츠과학부":["스포츠과학부":""],
//     "약학대학":["약학전공":"",
//             "제약학전공":""],
//     "예술대학":["디자인학과":"",
//             "무용학과":"",
//             "미술학과":"",
//             "예술문화영상학과":"",
//             "음악학과":"",
//             "조형학과":"",
//             "한국음악학과":""],
//     "의과대학":["의예과":"",
//             "의학과":""],
//     "인문대":["국어국문학과":"",
//            "고고학과":"",
//            "노어노문학과":"",
//            "독어독문학과":"",
//            "불어불문학과":"",
//            "사학과":"",
//            "언어정보학과":"",
//            "영어영문학과":"",
//            "일어일문학과":"",
//            "중어중문학과":"",
//            "철학과":"",
//            "한문학과":""],
//     "자연과학대학":["대기환경과학과":"",
//               "물리학과":"",
//               "미생물학과":"",
//               "분자생물학과":"",
//               "생명과학과":"",
//               "수학과":"",
//               "지질환경과학과":"",
//               "통계학과":"",
//               "해양학과":"",
//               "화학과":""],
//     "정보의생명공학대학":["정보컴퓨터공학부":"https://cse.pusan.ac.kr",
//                  "의생명융합공학부":""]]
    
    var collegeList: [String] = ["간호대학", "경영대학", "경제통상대학", "공과대학", "나노과학기술대학", "사범대학", "사회과학대학", "생명자원과학대학", "생활환경대학", "스포츠과학부", "약학대학", "예술대학", "의과대학", "인문대학", "자연과학대학", "정보의생명공학대학"]
    
    var departmentList : [String:[String]] =
    ["간호대학":["간호학과"],
     "경영대학":["경영학과"],
     "경제통상대학":["경제학부","공공정책학부","관광컨벤션학과","국제학부","무역학부"],
     "공과대학":["건설융합학부 건축공학전공","건설융합학부 건축학전공","건설융합학부 도시공학전공","건설융합학부 토목공학전공","고분자공학과","기계공학부","산업공학과","유기소재시스템공학과","재료공학부","전기공학과","전자공학과","조선해양공학과","항공우주공학과","화공생명환경공학부 화공생명공학전공","화공생명환경공학부 환경공학전공"],
     "나노과학기술대학":["광메카트로닉스공학과","나노메카트로닉스공학과","나노에너지공학과"],
     "사범대학":["교육학과","국어교육과","독어교육과","물리교육과","불어교육과","생물교육과","수학교육과","역사교육과","영어교육과","유아교육과","윤리교육과","일반사회교육과","지구과학교육과","지리교육과","체육교육과","특수교육과","화학교육과"],
     "사회과학대학":["문헌정보학과","미디어커뮤니케이션학과","사회복지학과","사회학과","심리학과","정치외교학과","행정학과"],
     "생명자원과학대학":["동물생명자원과학과","바이오산업기계공학과","바이오소재과학과","바이오환경에너지학과","생명환경화학과","식물생명과학과","식품공학과","식품자원경제학과","원예생명과학과","조경학과","IT응용공학과"],
     "생활환경대학":["식품영양학과","실내환경디자인학과","아동가족학과","의류학과"],
     "스포츠과학부":["스포츠과학부"],
     "약학대학":["약학전공","제약학전공"],
     "예술대학":["디자인학과","무용학과","미술학과","예술문화영상학과","음악학과","조형학과","한국음악학과"],
     "의과대학":["의예과","의학과"],
     "인문대학":["국어국문학과","고고학과","노어노문학과","독어독문학과","불어불문학과","사학과","언어정보학과","영어영문학과","일어일문학과","중어중문학과","철학과","한문학과"],
     "자연과학대학":["대기환경과학과","물리학과","미생물학과","분자생물학과","생명과학과","수학과","지질환경과학과","통계학과","해양학과","화학과"],
     "정보의생명공학대학":["정보컴퓨터공학부","의생명융합공학부"]]
    
    /// // 이 표시 있는 건 공지사항에 '장학' 카테고리 따로 있음
    /// 없으면 공지사항에서 '장학' 키워드 직접 검색
    var originURL: [String:String] =
    ["간호학과":"https://nursing.pusan.ac.kr",//
     "경영학과":"https://biz.pusan.ac.kr",
     "경제학부":"https://pnuecon.pusan.ac.kr",
     "공공정책학부":"https://ppm.pusan.ac.kr",
     "관광컨벤션학과":"https://convention.pusan.ac.kr",
     "국제학부":"https://pnudgs.com/board", ///공지사항 이상함. 링크 수정해야함
     "무역학부":"https://pnutrade.pusan.ac.kr", //
     "건설융합학부 건축공학전공":"https://archieng.pusan.ac.kr",
     "건설융합학부 건축학전공":"https://archi.pusan.ac.kr",
     "건설융합학부 도시공학전공":"https://urban.pusan.ac.kr",
     "건설융합학부 토목공학전공":"https://civil.pusan.ac.kr",
     "고분자공학과":"https://polymer.pusan.ac.kr",    //
     "기계공학부":"",    //함수 따로 빼줘야할듯
     "산업공학과":"https://ie.pusan.ac.kr",
     "유기소재시스템공학과":"https://omse.pusan.ac.kr",
     "재료공학부":"https://mse.pusan.ac.kr",
     "전기공학과":"https://eec.pusan.ac.kr",
     "전자공학과":"https://ee.pusan.ac.kr",
     "조선해양공학과":"https://naoe.pusan.ac.kr",
     "항공우주공학과":"https://aerospace.pusan.ac.kr",
     "화공생명환경공학부 화공생명공학전공":"https://chemeng.pusan.ac.kr",
     "화공생명환경공학부 환경공학전공":"https://pnuenv.pusan.ac.kr",
     "광메카트로닉스공학과":"https://ome.pusan.ac.kr",   //
     "나노메카트로닉스공학과":"https://nanomecha.pusan.ac.kr", //
     "나노에너지공학과":"https://energy.pusan.ac.kr",   //
     "교육학과":"https://ed.pusan.ac.kr",
     "국어교육과":"https://koredu.pusan.ac.kr",
     "독어교육과":"https://geredu.pusan.ac.kr",
     "물리교육과":"https://physedu.pusan.ac.kr",
     "불어교육과":"https://fredu.pusan.ac.kr",
     "생물교육과":"https://edubio.pusan.ac.kr",
     "수학교육과":"https://mathedu.pusan.ac.kr",
     "역사교육과":"https://hisedu.pusan.ac.kr",
     "영어교육과":"https://englishedu.pusan.ac.kr",
     "유아교육과":"https://child.pusan.ac.kr",
     "윤리교육과":"https://ethics.pusan.ac.kr",
     "일반사회교육과":"https://socialedu.pusan.ac.kr",
     "지구과학교육과":"https://earth.pusan.ac.kr",
     "지리교육과":"https://geoedu.pusan.ac.kr",
     "체육교육과":"https://physicaledu.pusan.ac.kr",
     "특수교육과":"https://special.pusan.ac.kr",
     "화학교육과":"https://chemedu.pusan.ac.kr",
     "문헌정보학과":"https://lais.pusan.ac.kr",   //
     "미디어커뮤니케이션학과":"https://comm.pusan.ac.kr",
     "사회복지학과":"https://swf.pusan.ac.kr",
     "사회학과":"https://soc.pusan.ac.kr",  //
     "심리학과":"https://psy.pusan.ac.kr",
     "정치외교학과":"https://polsci.pusan.ac.kr",
     "행정학과":"https://pub-adm.pusan.ac.kr",
     "동물생명자원과학과":"https://animal.pusan.ac.kr",
     "바이오산업기계공학과":"https://bime.pusan.ac.kr",
     "바이오소재과학과":"https://bm.pusan.ac.kr",
     "바이오환경에너지학과":"https://bee.pusan.ac.kr",
     "생명환경화학과":"https://pnu-lseb.pusan.ac.kr",
     "식물생명과학과":"https://plant.pusan.ac.kr",
     "식품공학과":"https://fst.pusan.ac.kr",
     "식품자원경제학과":"https://agecon.pusan.ac.kr",   //
     "원예생명과학과":"https://his.pusan.ac.kr",   //
     "조경학과":"https://la.pusan.ac.kr",
     "IT응용공학과":"https://ite.pusan.ac.kr",
     "식품영양학과":"https://fsn.pusan.ac.kr",
     "실내환경디자인학과":"https://hid.pusan.ac.kr",
     "아동가족학과":"https://cdfs.pusan.ac.kr",
     "의류학과":"https://fashion.pusan.ac.kr",
     "스포츠과학부":"https://sportscience.pusan.ac.kr",
     "약학전공":"https://pharmacy.pusan.ac.kr",
     "제약학전공":"https://pharmacy.pusan.ac.kr",
     "디자인학과":"https://design.pusan.ac.kr",
     "무용학과":"https://dance.pusan.ac.kr",
     "미술학과":"https://pnuart.pusan.ac.kr",
     "예술문화영상학과":"https://artimage.pusan.ac.kr",
     "음악학과":"https://music.pusan.ac.kr",
     "조형학과":"https://plarts.pusan.ac.kr",
     "한국음악학과":"https://gukak.pusan.ac.kr",
     "의예과":"https://medicine.pusan.ac.kr",
     "의학과":"https://medicine.pusan.ac.kr",
     "국어국문학과":"https://bkorea.pusan.ac.kr",
     "고고학과":"https://archaeology.pusan.ac.kr",  //
     "노어노문학과":"https://russia.pusan.ac.kr",
     "독어독문학과":"https://german.pusan.ac.kr",
     "불어불문학과":"https://french.pusan.ac.kr",
     "사학과":"https://history.pusan.ac.kr",
     "언어정보학과":"https://linguistics.pusan.ac.kr",
     "영어영문학과":"https://pnuenglish.pusan.ac.kr",
     "일어일문학과":"https://japan.pusan.ac.kr",
     "중어중문학과":"https://china.pusan.ac.kr",  //
     "철학과":"https://philosophy.pusan.ac.kr",
     "한문학과":"https://hanmun.pusan.ac.kr",
     "대기환경과학과":"https://atmos.pusan.ac.kr",
     "물리학과":"https://phys.pusan.ac.kr",
     "미생물학과":"https://microbio.pusan.ac.kr",
     "분자생물학과":"https://molbiology.pusan.ac.kr",
     "생명과학과":"https://biology.pusan.ac.kr", //
     "수학과":"https://math.pusan.ac.kr",
     "지질환경과학과":"https://geology.pusan.ac.kr",
     "통계학과":"https://stat.pusan.ac.kr",
     "해양학과":"https://ocean.pusan.ac.kr",    //
     "화학과":"https://chem.pusan.ac.kr",
     "정보컴퓨터공학부":"https://cse.pusan.ac.kr",
     "의생명융합공학부":"https://bce.pusan.ac.kr"]  //
    
    var detailURL: [String:String] =
    ["간호학과":"/nursing/14523/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbnVyc2luZyUyRjI1ODQlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "경영학과":"/biz/48589/subview.do",
     "경제학부":"/pnuecon/16317/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcG51ZWNvbiUyRjMyMTAlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "공공정책학부":"/ppm/17493/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcHBtJTJGMzQ5OCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "관광컨벤션학과":"/convention/16780/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGY29udmVudGlvbiUyRjMzNDYlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "국제학부":"/bbs/board.php?bo_table=Notice",
     "무역학부":"/pnutrade/16959/subview.do",
     "건설융합학부 건축공학전공":"/_archieng/20232/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGX2FyY2hpZW5nJTJGMzk2NCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "건설융합학부 건축학전공":"/archi/49898/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYXJjaGklMkYxMTkyMCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "건설융합학부 도시공학전공":"/urban/17084/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGdXJiYW4lMkYzNDEzJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "건설융합학부 토목공학전공":"/civil/16275/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGY2l2aWwlMkYzMjA3JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "고분자공학과":"/polymer/16546/subview.do",
     "기계공학부":"",
     "산업공학과":"/ie/19424/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGaWUlMkYzODEwJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "유기소재시스템공학과":"/omse/16246/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGb21zZSUyRjMyMDMlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "재료공학부":"/mse/38585/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbXNlJTJGODk3MiUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "전기공학과":"/eehome/14870/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZWVob21lJTJGMjY1MCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "전자공학과":"/ee/ug-notice.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZWUlMkYyNjM1JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "조선해양공학과":"/naoe/15332/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbmFvZSUyRjI3NTQlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "항공우주공학과":"/aerospace/16375/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYWVyb3NwYWNlJTJGMzIxMyUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "화공생명환경공학부 화공생명공학전공":"/chemeng/15735/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGY2hlbWVuZyUyRjI4NzAlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "화공생명환경공학부 환경공학전공":"/pnuenv/15177/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcG51ZW52JTJGMjcxNyUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "광메카트로닉스공학과":"/ome/16653/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGb21lJTJGMzMwOCUyRmFydGNsTGlzdC5kbyUzRg%3D%3D",
     "나노메카트로닉스공학과":"/nanomecha/16508/subview.do",
     "나노에너지공학과":"/energy/15620/subview.do",
     "교육학과":"/ed/15398/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZWQlMkYyNzY4JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "국어교육과":"/koredu/26185/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGa29yZWR1JTJGNTI2MiUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "독어교육과":"/geredu/21925/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZ2VyZWR1JTJGNDM4MSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "물리교육과":"/physedu/16992/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcGh5c2VkdSUyRjM0MDMlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "불어교육과":"/fredu/21987/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZnJlZHUlMkY0Mzk4JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "생물교육과":"/edubio/21256/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZWR1YmlvJTJGNDIzMSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "수학교육과":"/mathedu/15093/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbWF0aGVkdSUyRjI2OTYlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "역사교육과":"/hisedu/16873/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGaGlzZWR1JTJGMzM2MSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "영어교육과":"/englishedupnu/38204/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZW5nbGlzaGVkdXBudSUyRjg3ODklMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "유아교육과":"/child/15985/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGY2hpbGQlMkYzMTI5JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "윤리교육과":"/ethics/21795/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZXRoaWNzJTJGNDM1MSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "일반사회교육과":"/socialedu/20695/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGc29jaWFsZWR1JTJGNDEwMiUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "지구과학교육과":"/earth/23354/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZWFydGglMkY0NjU0JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "지리교육과":"/geoedu/21599/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZ2VvZWR1JTJGNDMxMCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "체육교육과":"/physicaledu/21846/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcGh5c2ljYWxlZHUlMkY0MzU4JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "특수교육과":"/special/17389/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGc3BlY2lhbCUyRjM0NzAlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "화학교육과":"/chemedu/20618/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGY2hlbWVkdSUyRjQwOTQlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "문헌정보학과":"/lais/62716/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbGFpcyUyRjE1NzMyJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QyNzglMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "미디어커뮤니케이션학과":"/comm/16750/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGY29tbSUyRjMzMzYlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "사회복지학과":"/swf/16699/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGc3dmJTJGMzMxNCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "사회학과":"/soc/42010/subview.do",
     "심리학과":"/psy/15495/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcHN5JTJGMjc5MiUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "정치외교학과":"/polsci/15686/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcG9sc2NpJTJGMjgzNyUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "행정학과":"/pub-adm/15295/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcHViLWFkbSUyRjI3NDQlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "동물생명자원과학과":"/animal/16623/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYW5pbWFsJTJGMzI5MyUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "바이오산업기계공학과":"/bime/19546/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYmltZSUyRjM4MzUlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "바이오소재과학과":"/bm/16433/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYm0lMkYzMjM0JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "바이오환경에너지학과":"/bee/19926/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYmVlJTJGMzkwNSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "생명환경화학과":"/pnu-lseb/21666/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcG51LWxzZWIlMkY0MzI0JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "식물생명과학과":"/plant/21365/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcGxhbnQlMkY0MjUyJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "식품공학과":"/fst/20152/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZnN0JTJGMzk1MCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "식품자원경제학과":"/agecon/20884/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYWdlY29uJTJGNDExNiUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEMTc3JTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "원예생명과학과":"/horticulture/21128/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGaG9ydGljdWx0dXJlJTJGNDE4MiUyRmFydGNsTGlzdC5kbyUzRg%3D%3D",
     "조경학과":"/la/20545/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbGElMkY0MDQxJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "IT응용공학과":"/ite/16028/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGaXRlJTJGMzE0MCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "식품영양학과":"/fsn/15462/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZnNuJTJGMjc4MyUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "실내환경디자인학과":"/hid/17458/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGaGlkJTJGMzQ4OSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "아동가족학과":"/cdfs/17266/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGY2RmcyUyRjM0NDklMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "의류학과":"/fashion/17222/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZmFzaGlvbiUyRjM0NDIlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "스포츠과학부":"/sportscience/14558/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGc3BvcnRzY2llbmNlJTJGMjU5MSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "약학전공":"/pharmacy/13582/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcGhhcm1hY3klMkYyNDIwJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "제약학전공":"/pharmacy/13582/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcGhhcm1hY3klMkYyNDIwJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "디자인학과":"/design/16811/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZGVzaWduJTJGMzM1MyUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "무용학과":"/dance/21024/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZGFuY2UlMkY0MTY0JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "미술학과":"/pnuart/20095/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcG51YXJ0JTJGMzk0MSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "예술문화영상학과":"/artimage/16476/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYXJ0aW1hZ2UlMkYzMjU3JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "음악학과":"/music/16183/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbXVzaWMlMkYzMTkyJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "조형학과":"/plarts/22177/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcGxhcnRzJTJGNDQzNCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "한국음악학과":"/gukak/20347/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZ3VrYWslMkYzOTc4JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "의예과":"/medicine/11950/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbWVkaWNpbmUlMkYyMjU3JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "의학과":"/medicine/11955/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbWVkaWNpbmUlMkYyMjYwJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "국어국문학과":"/bkorea/16906/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYmtvcmVhJTJGMzM3NSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "고고학과":"/archaeology/21071/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYXJjaGFlb2xvZ3klMkY0MTY3JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QyODglMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "노어노문학과":"/russia/63860/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcnVzc2lhJTJGMTYwNjElMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "독어독문학과":"/german/31506/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZ2VybWFuJTJGNjg2MCUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "불어불문학과":"/french/21555/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZnJlbmNoJTJGNDI5NSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "사학과":"/history/17355/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGaGlzdG9yeSUyRjM0NjYlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "언어정보학과":"/linguistics/20939/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbGluZ3Vpc3RpY3MlMkY0MTMzJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "영어영문학과":"/pnuenglish/15940/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcG51ZW5nbGlzaCUyRjMxMDglMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "일어일문학과":"/japan/17131/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGamFwYW4lMkYzNDIyJTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "중어중문학과":"/china/26560/subview.do",
     "철학과":"/philosophy/17294/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcGhpbG9zb3BoeSUyRjM0NTMlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "한문학과":"/hanmun/20474/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGaGFubXVuJTJGNDAwMSUyRmFydGNsTGlzdC5kbyUzRnNyY2hXcmQlM0QlMjVFQyUyNTlFJTI1QTUlMjVFRCUyNTk1JTI1OTklMjZzcmNoQ29sdW1uJTNEc2olMjZiYnNPcGVuV3JkU2VxJTNEJTI2aXNWaWV3TWluZSUzRGZhbHNlJTI2YmJzQ2xTZXElM0QlMjY%3D",
     "대기환경과학과":"/atmos/15905/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYXRtb3MlMkYzMDk2JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "물리학과":"/phys/14948/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGcGh5cyUyRjI2NTglMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "미생물학과":"/microbio/15867/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbWljcm9iaW8lMkYzMDg1JTJGYXJ0Y2xMaXN0LmRvJTNGc3JjaFdyZCUzRCUyNUVDJTI1OUUlMjVBNSUyNUVEJTI1OTUlMjU5OSUyNnNyY2hDb2x1bW4lM0RzaiUyNmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "분자생물학과":"/molbiology/19994/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbW9sYmlvbG9neSUyRjM5MTglMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "생명과학과":"/biology/16045/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYmlvbG9neSUyRjMxNDMlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRDklMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZiYnNDbFNlcSUzRCUyNg%3D%3D",
     "수학과":"/math/66565/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGbWF0aCUyRjI4MTglMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "지질환경과학과":"/geology/15533/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGZ2VvbG9neSUyRjI4MDAlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "통계학과":"/stat/15128/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGc3RhdCUyRjI3MDUlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "해양학과":"/ocean/15783/subview.do",
     "화학과":"/chem/15255/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGY2hlbSUyRjI3MzQlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI1RUMlMjU5RSUyNUE1JTI1RUQlMjU5NSUyNTk5JTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEJTI2",
     "정보컴퓨터공학부":"/cse/14651/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGY3NlJTJGMjYwNSUyRmFydGNsTGlzdC5kbyUzRmJic09wZW5XcmRTZXElM0QlMjZpc1ZpZXdNaW5lJTNEZmFsc2UlMjZzcmNoQ29sdW1uJTNEc2olMjZwYWdlJTNEMSUyNnNyY2hXcmQlM0QlMjZyZ3NCZ25kZVN0ciUzRCUyNmJic0NsU2VxJTNENDIyOSUyNnJnc0VuZGRlU3RyJTNEJTI2",
     "의생명융합공학부":"/bce/50189/subview.do?enc=Zm5jdDF8QEB8JTJGYmJzJTJGYmNlJTJGMTIwMDUlMkZhcnRjbExpc3QuZG8lM0ZzcmNoV3JkJTNEJTI2c3JjaENvbHVtbiUzRHNqJTI2YmJzT3BlbldyZFNlcSUzRCUyNmlzVmlld01pbmUlM0RmYWxzZSUyNmJic0NsU2VxJTNEOTg0OSUyNg%3D%3D"]
}
